/* Automatically generated by po2tbl.sed from xinvaders.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {" Start", 2},
  {"Error in row", 3},
  {"Error in column", 4},
  {" Quit ", 5},
  {" Info ", 6},
  {"Score", 7},
  {"High", 8},
  {"Error reading vshot images.\n", 9},
  {"Error reading Spacer image\n", 10},
  {"Error reading Invader images\n", 11},
  {"Pause", 12},
  {"Resume", 13},
  {"Xinvaders, by Jonny Goldman", 14},
  {"by Jonny Goldman", 15},
};

int _msg_tbl_length = 15;
